const STORE='unimanager_iq_students_v1';
const DEFAULT_STUDENTS=[
  {id:'1',number:'10001',name:'أحمد محمد علي',dept:'علوم مالية ومصرفية',stage:'الأولى',study:'صباحية',fee:1800000,paid:900000},
  {id:'2',number:'10002',name:'سارة حسن كريم',dept:'إدارة الأعمال',stage:'الثانية',study:'مسائية',fee:1600000,paid:1200000},
  {id:'3',number:'10003',name:'علي ماجد جواد',dept:'القانون',stage:'الثالثة',study:'صباحية',fee:2000000,paid:2000000}
];
let students=JSON.parse(localStorage.getItem(STORE)||'null')||DEFAULT_STUDENTS;
const qs=s=>document.querySelector(s); const qsa=s=>document.querySelectorAll(s);
const fmt=n=>new Intl.NumberFormat('ar-IQ').format(Number(n||0))+' د.ع';
function save(){localStorage.setItem(STORE,JSON.stringify(students));renderAll()}
function login(){qs('#loginView').classList.add('hidden');qs('#appView').classList.remove('hidden');}
qs('#loginForm').addEventListener('submit',e=>{e.preventDefault();if(qs('#username').value==='admin'&&qs('#password').value==='admin123')login();else alert('بيانات الدخول غير صحيحة');});
qs('#logoutBtn').addEventListener('click',()=>{qs('#appView').classList.add('hidden');qs('#loginView').classList.remove('hidden')});
function showPage(page){qsa('.page').forEach(x=>x.classList.add('hidden'));qs('#'+page+'Page').classList.remove('hidden');qsa('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:'لوحة التحكم',students:'إدارة الطلبة',finance:'الأقساط والحسابات',grades:'الدرجات',reports:'التقارير'};qs('#pageTitle').textContent=titles[page]||page;}
qsa('.nav-item').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
qsa('[data-page-jump]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.pageJump)));
qs('#dateNow').textContent=new Intl.DateTimeFormat('ar-IQ',{dateStyle:'full'}).format(new Date());
function renderDashboard(){const total=students.length,expected=students.reduce((s,x)=>s+Number(x.fee),0),paid=students.reduce((s,x)=>s+Number(x.paid),0),remaining=expected-paid;qs('#statStudents').textContent=total;qs('#statExpected').textContent=fmt(expected);qs('#statPaid').textContent=fmt(paid);qs('#statRemaining').textContent=fmt(remaining);qs('#financeSummary').innerHTML=`<div><strong style="font-size:28px">${expected?Math.round(paid/expected*100):0}%</strong><div class="muted">نسبة التحصيل الإجمالية</div></div>`;qs('#recentStudents').innerHTML=students.slice(-5).reverse().map(s=>`<div class="recent-row"><span>${s.name}<small class="muted"> — ${s.dept}</small></span><strong>${fmt(s.paid)}</strong></div>`).join('')||'<div class="empty-state">لا توجد بيانات</div>';}
function renderDepartments(){const depts=[...new Set(students.map(s=>s.dept).filter(Boolean))];const sel=qs('#studentDeptFilter');const cur=sel.value;sel.innerHTML='<option value="">كل الأقسام</option>'+depts.map(d=>`<option>${d}</option>`).join('');sel.value=depts.includes(cur)?cur:'';}
function renderStudents(){renderDepartments();const search=qs('#studentSearch').value.trim().toLowerCase(),dept=qs('#studentDeptFilter').value;const rows=students.filter(s=>(!search||[s.number,s.name,s.dept,s.stage].join(' ').toLowerCase().includes(search))&&(!dept||s.dept===dept));qs('#studentsTable').innerHTML=rows.map(s=>`<tr><td>${s.number}</td><td><strong>${s.name}</strong></td><td>${s.dept}</td><td>${s.stage}</td><td>${s.study}</td><td>${fmt(s.fee)}</td><td>${fmt(s.paid)}</td><td><button class="action-btn" onclick="editStudent('${s.id}')">تعديل</button><button class="action-btn danger-btn" onclick="deleteStudent('${s.id}')">حذف</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty-state">لا توجد نتائج</td></tr>';}
function renderFinance(){qs('#financeTable').innerHTML=students.map(s=>{const rem=Math.max(0,Number(s.fee)-Number(s.paid));const pct=s.fee?Math.round(Number(s.paid)/Number(s.fee)*100):0;return `<tr><td>${s.name}<div class="muted">${s.number}</div></td><td>${fmt(s.fee)}</td><td>${fmt(s.paid)}</td><td>${fmt(rem)}</td><td>${pct}%</td></tr>`}).join('')||'<tr><td colspan="5" class="empty-state">لا توجد بيانات</td></tr>';}
function renderAll(){renderDashboard();renderStudents();renderFinance();fillPaymentStudents();}
qs('#studentSearch').addEventListener('input',renderStudents);qs('#studentDeptFilter').addEventListener('change',renderStudents);
function openStudent(id=''){const s=students.find(x=>x.id===id);qs('#studentDialogTitle').textContent=s?'تعديل طالب':'إضافة طالب';qs('#studentId').value=s?.id||'';qs('#sNumber').value=s?.number||'';qs('#sName').value=s?.name||'';qs('#sDept').value=s?.dept||'';qs('#sStage').value=s?.stage||'الأولى';qs('#sStudy').value=s?.study||'صباحية';qs('#sFee').value=s?.fee??'';qs('#sPaid').value=s?.paid??'';qs('#studentDialog').showModal();}
window.editStudent=id=>openStudent(id); window.deleteStudent=id=>{const s=students.find(x=>x.id===id);if(confirm(`حذف الطالب ${s?.name}؟`)){students=students.filter(x=>x.id!==id);save();}};window.closeDialog=id=>qs('#'+id).close();
qs('#addStudentBtn').addEventListener('click',()=>openStudent());
qs('#studentForm').addEventListener('submit',e=>{e.preventDefault();const id=qs('#studentId').value;const data={id:id||crypto.randomUUID(),number:qs('#sNumber').value.trim(),name:qs('#sName').value.trim(),dept:qs('#sDept').value.trim(),stage:qs('#sStage').value,study:qs('#sStudy').value,fee:Number(qs('#sFee').value),paid:Number(qs('#sPaid').value)};if(id)students=students.map(x=>x.id===id?data:x);else students.push(data);qs('#studentDialog').close();save();});
function fillPaymentStudents(){qs('#pStudent').innerHTML=students.map(s=>`<option value="${s.id}">${s.number} — ${s.name}</option>`).join('');}
qs('#addPaymentBtn').addEventListener('click',()=>{fillPaymentStudents();qs('#pAmount').value='';qs('#paymentDialog').showModal()});
qs('#paymentForm').addEventListener('submit',e=>{e.preventDefault();const id=qs('#pStudent').value,amount=Number(qs('#pAmount').value);students=students.map(s=>s.id===id?{...s,paid:Number(s.paid)+amount}:s);qs('#paymentDialog').close();save();});
function downloadWorkbook(rows,name){const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'البيانات');XLSX.writeFile(wb,name);}
function exportStudents(){downloadWorkbook(students.map(s=>({الرقم:s.number,'اسم الطالب':s.name,القسم:s.dept,المرحلة:s.stage,الدراسة:s.study,'القسط الكلي':s.fee,'المدفوع':s.paid,'المتبقي':Math.max(0,s.fee-s.paid)})),'students-report.xlsx');}
function exportFinance(){downloadWorkbook(students.map(s=>({'رقم الطالب':s.number,'اسم الطالب':s.name,'القسط':s.fee,'المدفوع':s.paid,'المتبقي':Math.max(0,s.fee-s.paid),'نسبة التحصيل':s.fee?Math.round(s.paid/s.fee*100)+'%':'0%'})),'finance-report.xlsx');}
qs('#exportBtn').addEventListener('click',exportStudents);qs('#reportStudents').addEventListener('click',exportStudents);qs('#reportFinance').addEventListener('click',exportFinance);qs('#importBtn').addEventListener('click',()=>qs('#excelInput').click());
qs('#excelInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=await file.arrayBuffer();const wb=XLSX.read(data);const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const mapped=rows.map((r,i)=>({id:crypto.randomUUID(),number:String(r['الرقم']||r['رقم الطالب']||r['number']||i+1),name:r['اسم الطالب']||r['الاسم']||r['name']||'',dept:r['القسم']||r['dept']||'',stage:r['المرحلة']||r['stage']||'الأولى',study:r['الدراسة']||r['study']||'صباحية',fee:Number(r['القسط الكلي']||r['القسط']||r['fee']||0),paid:Number(r['المدفوع']||r['paid']||0)})).filter(x=>x.name);if(!mapped.length)throw new Error('لم يتم العثور على صفوف صالحة');students=[...students,...mapped];save();alert(`تم استيراد ${mapped.length} طالب بنجاح`);}catch(err){alert('تعذر استيراد الملف: '+err.message)}e.target.value='';});
renderAll();
