const STORES={students:"umi_students_v3",payments:"umi_payments_v3",departments:"umi_departments_v3",subjects:"umi_subjects_v3",grades:"umi_grades_v3"};
const defaults={
students:[
{id:"s1",number:"10001",name:"أحمد محمد علي",dept:"علوم مالية ومصرفية",stage:"الأولى",study:"صباحية",fee:1800000,paid:900000},
{id:"s2",number:"10002",name:"سارة حسن كريم",dept:"إدارة الأعمال",stage:"الثانية",study:"مسائية",fee:1600000,paid:1200000},
{id:"s3",number:"10003",name:"علي ماجد جواد",dept:"القانون",stage:"الثالثة",study:"صباحية",fee:2000000,paid:2000000}],
departments:[
{id:"d1",name:"علوم مالية ومصرفية",code:"FIN"},
{id:"d2",name:"إدارة الأعمال",code:"BUS"},
{id:"d3",name:"القانون",code:"LAW"}],
subjects:[
{id:"m1",name:"مبادئ المحاسبة",dept:"علوم مالية ومصرفية",stage:"الأولى",units:3},
{id:"m2",name:"مبادئ الإدارة",dept:"إدارة الأعمال",stage:"الثانية",units:3},
{id:"m3",name:"القانون المدني",dept:"القانون",stage:"الثالثة",units:4}]
};
const load=(key,def)=>JSON.parse(localStorage.getItem(STORES[key])||"null")??def;
let students=load("students",defaults.students),payments=load("payments",[]),departments=load("departments",defaults.departments),subjects=load("subjects",defaults.subjects),grades=load("grades",[]);
const qs=s=>document.querySelector(s), qsa=s=>document.querySelectorAll(s);
const normalizeDigits=v=>String(v??"").replace(/[٠-٩۰-۹]/g,c=>String("٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹".indexOf(c)%10));
const num=v=>Number(normalizeDigits(v).replace(/,/g,"").trim()||0);
const fmt=n=>new Intl.NumberFormat("en-US").format(Number(n||0))+" د.ع";
const save=()=>{localStorage.setItem(STORES.students,JSON.stringify(students));localStorage.setItem(STORES.payments,JSON.stringify(payments));localStorage.setItem(STORES.departments,JSON.stringify(departments));localStorage.setItem(STORES.subjects,JSON.stringify(subjects));localStorage.setItem(STORES.grades,JSON.stringify(grades));renderAll();};
function showPage(page){qsa(".page").forEach(x=>x.classList.add("hidden"));qs("#"+page+"Page").classList.remove("hidden");qsa(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));qs("#pageTitle").textContent={dashboard:"لوحة التحكم",students:"إدارة الطلبة",finance:"الأقساط والحسابات",grades:"الدرجات و Master Sheet",departments:"الأقسام والمواد",reports:"التقارير"}[page]||page;}
qsa(".nav-item").forEach(b=>b.onclick=()=>showPage(b.dataset.page));qsa("[data-page-jump]").forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));
qs("#loginForm").onsubmit=e=>{e.preventDefault();if(qs("#username").value==="admin"&&qs("#password").value==="admin123"){qs("#loginView").classList.add("hidden");qs("#appView").classList.remove("hidden");}else alert("بيانات الدخول غير صحيحة");};
qs("#logoutBtn").onclick=()=>{qs("#appView").classList.add("hidden");qs("#loginView").classList.remove("hidden");};
qs("#dateNow").textContent=new Intl.DateTimeFormat("ar-IQ",{dateStyle:"full"}).format(new Date());
function statusBadge(s){const r=Math.max(0,s.fee-s.paid),p=s.fee?Math.round(s.paid/s.fee*100):0;if(r<=0)return '<span class="badge success">مكتمل</span>';if(p>=50)return '<span class="badge warning">جزئي</span>';return '<span class="badge danger">متأخر</span>';}
function renderDashboard(){const exp=students.reduce((a,s)=>a+num(s.fee),0),paid=students.reduce((a,s)=>a+num(s.paid),0),rem=exp-paid,pct=exp?Math.round(paid/exp*100):0;qs("#statStudents").textContent=students.length;qs("#studentsHeroCount")&&(qs("#studentsHeroCount").textContent=students.length);qs("#financeHeroRemaining")&&(qs("#financeHeroRemaining").textContent=fmt(rem));qs("#gradesHeroCount")&&(qs("#gradesHeroCount").textContent=grades.length);qs("#deptHeroCount")&&(qs("#deptHeroCount").textContent=departments.length);qs("#statExpected").textContent=fmt(exp);qs("#statPaid").textContent=fmt(paid);qs("#statRemaining").textContent=fmt(rem);qs("#collectionPct").textContent=pct+"%";qs("#recentStudents").innerHTML=students.slice(-5).reverse().map(s=>`<div class="recent-row"><span>${s.name}<small class="muted"> — ${s.dept}</small></span><strong>${fmt(s.paid)}</strong></div>`).join("")||'<div class="empty-state">لا توجد بيانات</div>';}
function fillDeptSelect(id,all=true){const el=qs("#"+id),cur=el.value;el.innerHTML=(all?'<option value="">كل الأقسام</option>':"<option value=\"\">اختر القسم</option>")+departments.map(d=>`<option value="${d.name}">${d.name}</option>`).join("");el.value=departments.some(d=>d.name===cur)?cur:"";}
function renderStudentFilters(){fillDeptSelect("studentDeptFilter");fillDeptSelect("gradeDeptFilter");fillDeptSelect("sDept",false);fillDeptSelect("subDept",false);}
function renderStudents(){renderStudentFilters();const q=qs("#studentSearch").value.trim().toLowerCase(),d=qs("#studentDeptFilter").value,st=qs("#studentStageFilter").value;const rows=students.filter(s=>(!q||[s.number,s.name,s.dept,s.stage].join(" ").toLowerCase().includes(q))&&(!d||s.dept===d)&&(!st||s.stage===st));qs("#studentsTable").innerHTML=rows.map(s=>`<tr><td>${s.number}</td><td><strong>${s.name}</strong></td><td>${s.dept}</td><td>${s.stage}</td><td>${s.study}</td><td>${fmt(s.fee)}</td><td>${fmt(s.paid)}</td><td>${statusBadge(s)}</td><td><button class="action-btn" onclick="openProfile('${s.id}')">ملف</button><button class="action-btn" onclick="editStudent('${s.id}')">تعديل</button><button class="action-btn danger-btn" onclick="deleteStudent('${s.id}')">حذف</button></td></tr>`).join("")||'<tr><td colspan="9" class="empty-state">لا توجد نتائج</td></tr>';}
function renderFinance(){qs("#financeTable").innerHTML=students.map(s=>{const r=Math.max(0,num(s.fee)-num(s.paid)),p=s.fee?Math.round(num(s.paid)/num(s.fee)*100):0;return `<tr><td>${s.name}<div class="muted">${s.number}</div></td><td>${fmt(s.fee)}</td><td>${fmt(s.paid)}</td><td>${fmt(r)}</td><td>${p}%</td><td>${statusBadge(s)}</td><td><button class="action-btn" onclick="openPaymentFor('${s.id}')">دفعة</button></td></tr>`}).join("");}
function renderDepartments(){qs("#departmentsList").innerHTML=departments.map(d=>`<div class="list-row"><div><strong>${d.name}</strong><div class="muted">${d.code}</div></div><button class="small-btn" onclick="deleteDept('${d.id}')">حذف</button></div>`).join("")||'<div class="empty-state">لا توجد أقسام</div>';qs("#subjectsList").innerHTML=subjects.map(m=>`<div class="list-row"><div><strong>${m.name}</strong><div class="muted">${m.dept} — ${m.stage} — ${m.units} وحدات</div></div><button class="small-btn" onclick="deleteSubject('${m.id}')">حذف</button></div>`).join("")||'<div class="empty-state">لا توجد مواد</div>';}
function renderGradeFilters(){const sub=qs("#gradeSubjectFilter"),cur=sub.value;sub.innerHTML='<option value="">كل المواد</option>'+subjects.map(s=>`<option value="${s.id}">${s.name}</option>`).join("");sub.value=subjects.some(s=>s.id===cur)?cur:"";}
function renderGrades(){renderStudentFilters();renderGradeFilters();const d=qs("#gradeDeptFilter").value,st=qs("#gradeStageFilter").value,sub=qs("#gradeSubjectFilter").value;const rows=grades.filter(g=>{const s=students.find(x=>x.id===g.studentId),m=subjects.find(x=>x.id===g.subjectId);return s&&m&&(!d||s.dept===d)&&(!st||s.stage===st)&&(!sub||g.subjectId===sub)});qs("#gradesTable").innerHTML=rows.map(g=>{const s=students.find(x=>x.id===g.studentId),m=subjects.find(x=>x.id===g.subjectId),total=num(g.course)+num(g.final),pass=total>=50;return `<tr><td>${s?.name||""}<div class="muted">${s?.number||""}</div></td><td>${m?.name||""}</td><td>${g.course}</td><td>${g.final}</td><td><strong>${total}</strong></td><td class="${pass?"result-pass":"result-fail"}">${pass?"ناجح":"راسب"}</td><td><button class="action-btn danger-btn" onclick="deleteGrade('${g.id}')">حذف</button></td></tr>`}).join("")||'<tr><td colspan="7" class="empty-state">لا توجد درجات</td></tr>';}
function renderAll(){renderDashboard();renderStudents();renderFinance();renderDepartments();renderGrades();fillPaymentStudents();}
qs("#studentSearch").oninput=renderStudents;qs("#studentDeptFilter").onchange=renderStudents;qs("#studentStageFilter").onchange=renderStudents;qs("#gradeDeptFilter").onchange=renderGrades;qs("#gradeStageFilter").onchange=renderGrades;qs("#gradeSubjectFilter").onchange=renderGrades;
function openStudent(id=""){const s=students.find(x=>x.id===id);qs("#studentDialogTitle").textContent=s?"تعديل طالب":"إضافة طالب";qs("#studentId").value=s?.id||"";qs("#sNumber").value=s?.number||"";qs("#sName").value=s?.name||"";qs("#sDept").value=s?.dept||departments[0]?.name||"";qs("#sStage").value=s?.stage||"الأولى";qs("#sStudy").value=s?.study||"صباحية";qs("#sFee").value=s?.fee??"";qs("#sPaid").value=s?.paid??"";qs("#studentDialog").showModal();}
window.editStudent=openStudent;
window.deleteStudent=id=>{const s=students.find(x=>x.id===id);if(confirm(`حذف الطالب ${s?.name}؟`)){students=students.filter(x=>x.id!==id);payments=payments.filter(p=>p.studentId!==id);grades=grades.filter(g=>g.studentId!==id);save();}};
window.openProfile=id=>{const s=students.find(x=>x.id===id);const rem=Math.max(0,num(s.fee)-num(s.paid));const ps=payments.filter(p=>p.studentId===id).reverse();qs("#studentProfile").innerHTML=`<div class="profile-grid"><p><b>الرقم:</b> ${s.number}</p><p><b>الاسم:</b> ${s.name}</p><p><b>القسم:</b> ${s.dept}</p><p><b>المرحلة:</b> ${s.stage}</p><p><b>الدراسة:</b> ${s.study}</p><p><b>القسط:</b> ${fmt(s.fee)}</p><p><b>المدفوع:</b> ${fmt(s.paid)}</p><p><b>المتبقي:</b> ${fmt(rem)}</p></div><hr><h4>سجل الدفعات</h4>${ps.map(p=>`<div class="list-row"><span>${new Date(p.date).toLocaleDateString("en-GB")} — ${p.method} ${p.note?`— ${p.note}`:""}</span><strong>${fmt(p.amount)}</strong></div>`).join("")||'<div class="empty-state">لا توجد دفعات مسجلة</div>'}`;qs("#studentProfileDialog").showModal();};
window.closeDialog=id=>qs("#"+id).close();
qs("#addStudentBtn").onclick=()=>openStudent();
qs("#studentForm").onsubmit=e=>{e.preventDefault();const id=qs("#studentId").value,data={id:id||crypto.randomUUID(),number:normalizeDigits(qs("#sNumber").value),name:qs("#sName").value.trim(),dept:qs("#sDept").value,stage:qs("#sStage").value,study:qs("#sStudy").value,fee:num(qs("#sFee").value),paid:num(qs("#sPaid").value)};if(id)students=students.map(x=>x.id===id?data:x);else students.push(data);qs("#studentDialog").close();save();};
function fillPaymentStudents(){qs("#pStudent").innerHTML=students.map(s=>`<option value="${s.id}">${s.number} — ${s.name}</option>`).join("");}
window.openPaymentFor=id=>{fillPaymentStudents();qs("#pStudent").value=id;qs("#pAmount").value="";qs("#pNote").value="";qs("#paymentDialog").showModal();};
qs("#addPaymentBtn").onclick=()=>window.openPaymentFor(students[0]?.id||"");
qs("#paymentForm").onsubmit=e=>{e.preventDefault();const studentId=qs("#pStudent").value,amount=num(qs("#pAmount").value),s=students.find(x=>x.id===studentId);if(!s||amount<=0)return;const rem=Math.max(0,num(s.fee)-num(s.paid));if(amount>rem&&rem>0&&!confirm("المبلغ أكبر من المتبقي. هل تريد المتابعة؟"))return;s.paid=num(s.paid)+amount;payments.push({id:crypto.randomUUID(),studentId,amount,date:new Date().toISOString(),method:qs("#pMethod").value,note:qs("#pNote").value.trim()});qs("#paymentDialog").close();save();};
qs("#addGradeBtn").onclick=()=>{qs("#gStudent").innerHTML=students.map(s=>`<option value="${s.id}">${s.number} — ${s.name}</option>`).join("");qs("#gSubject").innerHTML=subjects.map(m=>`<option value="${m.id}">${m.name} — ${m.stage}</option>`).join("");qs("#gCourse").value="";qs("#gFinal").value="";qs("#gradeDialog").showModal();};
qs("#gradeForm").onsubmit=e=>{e.preventDefault();const studentId=qs("#gStudent").value,subjectId=qs("#gSubject").value;const old=grades.find(g=>g.studentId===studentId&&g.subjectId===subjectId);const data={id:old?.id||crypto.randomUUID(),studentId,subjectId,course:num(qs("#gCourse").value),final:num(qs("#gFinal").value)};grades=old?grades.map(g=>g.id===old.id?data:g):[...grades,data];qs("#gradeDialog").close();save();};
window.deleteGrade=id=>{grades=grades.filter(g=>g.id!==id);save();};
qs("#addDeptBtn").onclick=()=>{qs("#dName").value="";qs("#dCode").value="";qs("#deptDialog").showModal();};
qs("#deptForm").onsubmit=e=>{e.preventDefault();departments.push({id:crypto.randomUUID(),name:qs("#dName").value.trim(),code:normalizeDigits(qs("#dCode").value.trim())});qs("#deptDialog").close();save();};
window.deleteDept=id=>{const d=departments.find(x=>x.id===id);if(students.some(s=>s.dept===d?.name)||subjects.some(s=>s.dept===d?.name)){alert("لا يمكن حذف القسم لأنه مرتبط بطلبة أو مواد.");return;}departments=departments.filter(x=>x.id!==id);save();};
qs("#addSubjectBtn").onclick=()=>{fillDeptSelect("subDept",false);qs("#subName").value="";qs("#subStage").value="الأولى";qs("#subUnits").value="3";qs("#subjectDialog").showModal();};
qs("#subjectForm").onsubmit=e=>{e.preventDefault();subjects.push({id:crypto.randomUUID(),name:qs("#subName").value.trim(),dept:qs("#subDept").value,stage:qs("#subStage").value,units:num(qs("#subUnits").value)});qs("#subjectDialog").close();save();};
window.deleteSubject=id=>{if(grades.some(g=>g.subjectId===id)){alert("لا يمكن حذف المادة لأنها مرتبطة بدرجات.");return;}subjects=subjects.filter(x=>x.id!==id);save();};
function download(rows,name){const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,"البيانات");XLSX.writeFile(wb,name);}
function exportStudents(){download(students.map(s=>({الرقم:s.number,"اسم الطالب":s.name,القسم:s.dept,المرحلة:s.stage,الدراسة:s.study,"القسط الكلي":s.fee,"المدفوع":s.paid,"المتبقي":Math.max(0,s.fee-s.paid)})),"students-report.xlsx");}
function exportFinance(){download(students.map(s=>({"رقم الطالب":s.number,"اسم الطالب":s.name,"القسط":s.fee,"المدفوع":s.paid,"المتبقي":Math.max(0,s.fee-s.paid),"نسبة التحصيل":s.fee?Math.round(s.paid/s.fee*100)+"%":"0%",الحالة:s.fee<=s.paid?"مكتمل":s.paid>0?"جزئي":"متأخر"})),"finance-report.xlsx");}
function exportPayments(){download(payments.map(p=>{const s=students.find(x=>x.id===p.studentId);return{"رقم الطالب":s?.number||"","اسم الطالب":s?.name||"","المبلغ":p.amount,"التاريخ":new Date(p.date).toLocaleDateString("en-GB"),"طريقة الدفع":p.method,"الملاحظة":p.note||""};}),"payments-report.xlsx");}
function exportGrades(){download(grades.map(g=>{const s=students.find(x=>x.id===g.studentId),m=subjects.find(x=>x.id===g.subjectId),total=num(g.course)+num(g.final);return{"رقم الطالب":s?.number||"","اسم الطالب":s?.name||"","القسم":s?.dept||"","المرحلة":s?.stage||"","المادة":m?.name||"","السعي":g.course,"النهائي":g.final,"الدرجة النهائية":total,"النتيجة":total>=50?"ناجح":"راسب"};}),"grades-report.xlsx");}
function exportMaster(){const map={};grades.forEach(g=>{const s=students.find(x=>x.id===g.studentId),m=subjects.find(x=>x.id===g.subjectId);if(!s||!m)return;map[s.id]??={الرقم:s.number,"اسم الطالب":s.name,القسم:s.dept,المرحلة:s.stage};map[s.id][m.name]=num(g.course)+num(g.final);});download(Object.values(map),"master-sheet.xlsx");}
qs("#exportBtn").onclick=exportStudents;qs("#reportStudents").onclick=exportStudents;qs("#reportFinance").onclick=exportFinance;qs("#reportPayments").onclick=exportPayments;qs("#reportGrades").onclick=exportGrades;qs("#exportMasterBtn").onclick=exportMaster;
qs("#importBtn").onclick=()=>qs("#excelInput").click();
qs("#excelInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer());const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const mapped=rows.map((r,i)=>({id:crypto.randomUUID(),number:normalizeDigits(r["الرقم"]||r["رقم الطالب"]||r.number||i+1),name:r["اسم الطالب"]||r["الاسم"]||r.name||"",dept:r["القسم"]||r.dept||departments[0]?.name||"",stage:r["المرحلة"]||r.stage||"الأولى",study:r["الدراسة"]||r.study||"صباحية",fee:num(r["القسط الكلي"]||r["القسط"]||r.fee),paid:num(r["المدفوع"]||r.paid)})).filter(x=>x.name);if(!mapped.length)throw new Error("لم يتم العثور على صفوف صالحة");students=[...students,...mapped];save();alert(`تم استيراد ${mapped.length} طالب بنجاح`);}catch(err){alert("تعذر استيراد الملف: "+err.message)}e.target.value="";};
renderAll();